// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"======== JS","status":false,"description":"","parameters":{}},
{"name":"SC/core/JsExtension","status":true,"description":"!SC [v1.1.0] Extension des objets standards de JS","parameters":{}},
{"name":"======== CORE","status":false,"description":"","parameters":{}},
{"name":"SC_configs/SC_CoreConfig","status":true,"description":"!SC [v0.3.0] Configuration du Cœur Moteur de SimCraft","parameters":{"Debug - Environment Mode":"DEV","Debug - Enable Debug":"true","Debug - Deep Debug":"false"}},
{"name":"SC/core/DebugTool","status":true,"description":"!SC [v1.0.1] Outil de debug console de SimCraft Engine","parameters":{}},
{"name":"SC/core/SC_SystemLoader","status":true,"description":"!SC [v0.3.0] Chargeur de système, dépendances et instances.","parameters":{}},
{"name":"SC/core/InputExtension","status":true,"description":"!SC [v1.0.0] Extension du mapping de clavier de RMMZ.","parameters":{}},
{"name":"======== CONFIGS","status":false,"description":"","parameters":{}},
{"name":"SC_configs/SC_InputConfig","status":true,"description":"!SC [v1.0.0] Configuration des entrées pour SimCraft Engine","parameters":{"ok":"[\"enter\",\"space\",\"z\"]","cancel":"[\"escape\",\"insert\",\"numpad_0\",\"x\"]","shift":"[\"shift\"]","menu":"[\"x\"]","pageup":"[\"pageup\",\"q\"]","pagedown":"[\"pagedown\",\"w\"]","left":"[\"left\",\"numpad_4\"]","up":"[\"up\",\"numpad_8\"]","right":"[\"right\",\"numpad_6\"]","down":"[\"down\",\"numpad_2\"]","tab":"[\"tab\"]","control":"[\"control\",\"alt\"]","debug":"[\"f9\"]","defaultKeyMappings":"[\"{\\\"inputCode\\\":\\\"jump\\\",\\\"keyName\\\":\\\"P\\\"}\"]"}},
{"name":"SC_configs/SC_TouchInputConfig","status":true,"description":"!SC [v1.0.0] Configuration des entrées tactiles pour SimCraft Engine.","parameters":{"cancelOnRightClick":"false"}},
{"name":"======== CORE_MANAGERS","status":false,"description":"","parameters":{}},
{"name":"SC/managers/DataManager","status":true,"description":"!SC [v0.4.0] Gestionnaire de données étendu de SimCraft Engine","parameters":{}},
{"name":"SC/managers/InputManager","status":true,"description":"!SC [v1.0.0] Gestionnaire d'entrées dynamique pour SimCraft Engine.","parameters":{}},
{"name":"SC/managers/TouchInputManager","status":true,"description":"!SC [v1.0.1] Gestionnaire d'entrées tactiles et souris étendu.","parameters":{}},
{"name":"======== OTHER PLUGINS","status":false,"description":"","parameters":{}}
];
