//=============================================================================
// RPG Maker MZ - SC_WeatherConfig
//=============================================================================
/*:
 * @target MZ
 * @plugindesc [SC] Configuration for the Weather module.
 * @author SimCraft
 * @url https://github.com/simcraft-engine
 *
 * @help
 * This file defines the visual and audio properties for each weather type
 * used by the Game_Weather system.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

SC.weather = SC.weather || {};

SC.weather.config = {
    // No visual effect, just clears other effects
    "clear": { 
        overlay: null 
    },

    // A light cloud overlay
    "cloudy": { 
        overlay: "clouds_fast", 
        scrollX: -1.0, 
        scrollY: -0.3, 
        defaultIntensity: 150 // Opacity from 0 to 255
    },

    // Rain effect using native particles and a color overlay
    "rain":   { 
        overlay: "rain_effect", 
        scrollX: 6, 
        scrollY: 0, 
        defaultIntensity: 180, 
        native: { type: "rain", power: 4 } 
    },

    // Storm effect with more intense particles and overlay
    "storm":  { 
        overlay: "rain_effect", 
        scrollX: 2, 
        scrollY: 12, 
        defaultIntensity: 220, 
        native: { type: "storm", power: 7 } 
    },
    
    // Snow effect using native particles
    "snow": {
        overlay: null, // Could have a gentle white overlay
        defaultIntensity: 0,
        native: { type: "snow", power: 5 }
    }
};

//=============================================================================
// System Loader
//=============================================================================
SC._temp = SC._temp || {};
SC._temp.pluginRegister = {
    name: "SC_WeatherConfig",
    version: "1.0.0",
    icon: "🎨",
    author: AUTHOR,
    license: LICENCE,
    dependencies: ["SC_SystemLoader"],
    createObj: { autoCreate: false },
};
$simcraftLoader.checkPlugin(SC._temp.pluginRegister);

